### PR TITLE
Authorization goodies for tsecauthservice + possible bug fix for authenticators

### LINKED ISSUE #81: Howto Compose Authorized Services
Let's say I'm using an RBAC and i have several roles:

`Role.user`, `Role.customer`, `Role.vendor`

And I'm using an `SecuredRequestHandler` , I want to do something like like

```
handler.authorized(Role.user, Role.customer) { } <+> // can access
handler.authorized(Role.customer, Role.vendor) { } <+> // 404
handler { } // 404
```

requests to the right of the first authorized will 404 due to: https://github.com/http4s/http4s/pull/1530

Is there a way to compose routes that require different authorization?

### PR DESCRIPTION
**Pull request by jmcardon**
Closes #81 

- `onNotAuthorized` was wrong (my bad), I actually meant `onNotAuthenticated`
- There was no error handling within `parseRaw` for Authenticators. Given something may fail with `F.raiseError`, this shouldn't necessarily fall in the catch all handler. This should simply go immediately to the `onNotAuthenticated` handler (by being `OptionT.none)

### CODE REVIEW

File: tsec-http4s/src/main/scala/tsec/authentication/SecuredRequestHandler.scala [hunk 1]
```diff
@@ -43,16 +43,16 @@ sealed abstract class SecuredRequestHandler[F[_], Identity, User, Auth](
...
   /** Create an Authorized service from a TSecAuthService **/
   def liftAuthorizedService(
       authorization: Authorization[F, User, Auth],
       service: TSecAuthService[User, Auth, F],
-      onNotAuthorized: Request[F] => F[Response[F]] = defaultNotAuthorized
+      onNotAuthenticated: Request[F] => F[Response[F]] = defaultNotAuthenticated
   ): HttpService[F] =
-    authorizedMiddleware(authorization, onNotAuthorized)(service)
+    authorizedMiddleware(authorization, onNotAuthenticated)(service)
       .handleErrorWith(e => Kleisli.lift(OptionT.pure(cachedUnauthorized)))
```
Comment (rsoeldner) [inline tsec-http4s/src/main/scala/tsec/authentication/SecuredRequestHandler.scala]: `_ => Kleisli.lift(OptionT.pure(cachedUnauthorized))`

File: tsec-http4s/src/main/scala/tsec/authentication/SecuredRequestHandler.scala [hunk 2]
```diff
@@ -78,19 +78,19 @@ object SecuredRequestHandler {
...
 
       /** Create an Authorized Service **/
       def authorized(authorization: Authorization[F, User, Auth])(
           pf: PartialFunction[SecuredRequest[F, User, Auth], F[Response[F]]],
-          onNotAuthorized: Request[F] => F[Response[F]] = defaultNotAuthorized
+          onNotAuthenticated: Request[F] => F[Response[F]] = defaultNotAuthenticated
       ): HttpService[F] =
-        authorizedMiddleware(authorization, onNotAuthorized)(TSecAuthService(pf, authenticator.afterBlock))
+        authorizedMiddleware(authorization, onNotAuthenticated)(TSecAuthService(pf, authenticator.afterBlock))
           .handleErrorWith(e => Kleisli.lift(OptionT.pure(cachedUnauthorized)))
```
Comment (rsoeldner) [inline tsec-http4s/src/main/scala/tsec/authentication/SecuredRequestHandler.scala]: same

File: tsec-http4s/src/main/scala/tsec/authentication/SecuredRequestHandler.scala [hunk 3]
```diff
@@ -116,9 +116,9 @@ object SecuredRequestHandler {
       /** Create an Authorized Service **/
       def authorized(authorization: Authorization[F, User, Auth])(
           pf: PartialFunction[SecuredRequest[F, User, Auth], F[Response[F]]],
-          onNotAuthorized: Request[F] => F[Response[F]] = defaultNotAuthorized
+          onNotAuthenticated: Request[F] => F[Response[F]] = defaultNotAuthenticated
       ): HttpService[F] =
-        authorizedMiddleware(authorization, onNotAuthorized)(TSecAuthService(pf))
+        authorizedMiddleware(authorization, onNotAuthenticated)(TSecAuthService(pf))
           .handleErrorWith(e => Kleisli.lift(OptionT.pure(cachedUnauthorized)))
```
Comment (rsoeldner) [inline tsec-http4s/src/main/scala/tsec/authentication/SecuredRequestHandler.scala]: as above
