### PR TITLE
QOL fixes for tsec-http4s

### LINKED ISSUE #104: Add a simpler non-verified parsing of JWTMac
In some use cases, we might simpl want to check whether the repr is fine, without redoing the signing work.

### LINKED ISSUE #105: JWTAuthenticators AugmentedJWT might do redundant work
to get an `AugmentedJWT` from the backend, we kinda have to parse the JWT portion of it.

This is redundant work for verification... We do all this work for every request submitted from a client, we don't need to even do a simpler reparse at all, we just need to check the serialized, raw version against the raw version in the server and call it a day.

### LINKED ISSUE #114: Make <+> AuthedService composition optional for non-spidering

### PR DESCRIPTION
**Pull request by jmcardon**
A few classes for authenticators seem to be over-constrained. 

This is in a general move to not force authenticators to use the JCA, to eventually enable fips for authentication as well.

This PR deals with:
- Loosening constrains, and removing unneeded ones.
- Adding an example similar to #140, for all authenticators
- Adds unverified parsing for a `JWTMac`. Small enough stuff to where it can fit in this PR too. 

Closes #105 
Closes #104 
Closes #114 

Note: #143 and #144 merge into this one as a general improvement of the Http4s api, to separate more significant points:
- #143 deals with general improvements to `PasswordStore`, from a usability persective
- #144 adds a user aware service.

Merge this one after #143 and #144

### CODE REVIEW

File: examples/src/main/scala/http4sExamples/BearerTokenExample.scala [hunk 1]
```diff
@@ -54,4 +48,12 @@ object BearerTokenExample {
...
       Ok()
   }
+
+  val authedService2: AuthService = TSecAuthService {
+    case GET -> Root / "api2" asAuthed user =>
+      Ok()
+  }
+
+  val lifted: HttpService[IO] = Auth.liftService(authService1)
+  val liftedComposed: HttpService[IO] = Auth.liftService(authService1 <+> authedService2)
```
Comment (rsoeldner) [inline examples/src/main/scala/http4sExamples/BearerTokenExample.scala]: :+1:

File: examples/src/main/scala/http4sExamples/jwtStatefulExample.scala [hunk 2]
```diff
@@ -14,22 +15,24 @@ object jwtStatefulExample {
...
+    : MacSigningKey[HMACSHA256] = HMACSHA256.generateKey[Id] //Our signing key. Instantiate in a safe way using GenerateLift
 
   val jwtStatefulAuth =
     JWTAuthenticator.withBackingStore(
       expiryDuration = 10.minutes, //Absolute expiration time
-      maxIdle        = None,
-      tokenStore     = jwtStore,
-      identityStore  = userStore,
-      signingKey     = signingKey
+      maxIdle = None,
```
Comment (rsoeldner) [inline examples/src/main/scala/http4sExamples/jwtStatefulExample.scala]: what happens to your formating ?

File: jwt-mac/src/test/scala/tsec/JWTMacTests.scala [hunk 3]
```diff
@@ -59,6 +60,24 @@ class JWTMacTests extends TestSpec with MustMatchers {
       res.unsafeRunSync() mustBe true
     }
 
+    it should "parse unverified correctly" in {
+      val res = for {
+        key    <- keyGen.generateKey
+        claims <- JWTClaims.withDuration[IO](notBefore = Some(-2.seconds), expiration = Some(10.seconds))
```
Comment (rsoeldner) [inline jwt-mac/src/test/scala/tsec/JWTMacTests.scala]: Hm, I see negative seconds the first time, is this useful ?

File: tsec-http4s/src/main/scala/tsec/authentication/package.scala [hunk 4]
```diff
@@ -79,12 +96,12 @@ package object authentication {
       * [[org.http4s.Response.notFound]], which generates a 404, for any request
       * where `pf` is not defined.
       */
-    def apply[A, I, F[_]](
+    def apply[I, A, F[_]](
```
Comment (rsoeldner) [inline tsec-http4s/src/main/scala/tsec/authentication/package.scala]: this change was because of partial unification bug ?

File: tsec-http4s/src/main/scala/tsec/authentication/package.scala [hunk 5]
```diff
@@ -114,6 +131,62 @@ package object authentication {
       Kleisli.liftF(OptionT.none)
   }
 
+  type UserAwareService[Ident, A, F[_]] =
+    Kleisli[OptionT[F, ?], UserAwareRequest[F, Ident, A], Response[F]]
+
+  type UserAwareMiddleware[F[_], Ident, A] =
```
Comment (rsoeldner) [inline tsec-http4s/src/main/scala/tsec/authentication/package.scala]: `Ident` == `I` ?

File: tsec-http4s/src/main/scala/tsec/authentication/package.scala (hunk 4 above)
Comment (jmcardon) [reply tsec-http4s/src/main/scala/tsec/authentication/package.scala]: yes.

File: jwt-mac/src/test/scala/tsec/JWTMacTests.scala (hunk 3 above)
Comment (jmcardon) [reply jwt-mac/src/test/scala/tsec/JWTMacTests.scala]: `notBefore` will just give you some `now.plusSeconds(t)` when the token can't be used.

This simply ensures after callign that function, `notBefore` always is valid.

File: examples/src/main/scala/http4sExamples/jwtStatefulExample.scala (hunk 2 above)
Comment (jmcardon) [reply examples/src/main/scala/http4sExamples/jwtStatefulExample.scala]: idk ask scalafmt :(

File: tsec-http4s/src/main/scala/tsec/authentication/package.scala (hunk 5 above)
Comment (jmcardon) [reply tsec-http4s/src/main/scala/tsec/authentication/package.scala]: yeah, same thing. 

`Ident` is any `Identity`

Comment (rsoeldner) [reply tsec-http4s/src/main/scala/tsec/authentication/package.scala]: for consistency we should change to `I`, what do you think ?

File: tsec-http4s/src/main/scala/tsec/authentication/package.scala (hunk 4 above)
Comment (rsoeldner) [reply tsec-http4s/src/main/scala/tsec/authentication/package.scala]: :+1:

File: examples/src/main/scala/http4sExamples/jwtStatefulExample.scala (hunk 2 above)
Comment (rsoeldner) [reply examples/src/main/scala/http4sExamples/jwtStatefulExample.scala]: haha :fire:

File: tsec-http4s/src/main/scala/tsec/authentication/package.scala (hunk 5 above)
Comment (jmcardon) [reply tsec-http4s/src/main/scala/tsec/authentication/package.scala]: I don't disagree, sure. but `Ident` is also on `TSecAuthService`. Would you mind pushing to my branch real quick? I'm off to bed :)

File: tsec-http4s/src/main/scala/tsec/authentication/package.scala (hunk 4 above)
Comment (jmcardon) [reply tsec-http4s/src/main/scala/tsec/authentication/package.scala]: Also to be clear: `A, I, F[_]` was changed because of the partial unification bug, then the swap to `I, A, F` was because the result type is `I, A, F`. It felt weird to hvae the type params in the apply method in different order of the result type.

File: tsec-http4s/src/main/scala/tsec/authentication/package.scala (hunk 5 above)
Comment (rsoeldner) [reply tsec-http4s/src/main/scala/tsec/authentication/package.scala]: :+1:
